In [34]:
import numpy as np
import pandas as pd

In [3]:
# 1. Create a NumPy array ‘arr’ of integers from 0 to 5 and print its data type. 

arr1 = np.array([0,1,2,3,4,5], dtype=int)
print(arr1)
print(arr1.dtype)

[0 1 2 3 4 5]
int64


In [4]:
# 2. Given a NumPy array ‘arr’, check if its data type is float64. 
arr = np.array([1.5, 2.6, 3.7]) 
print(arr.dtype)

float64


In [5]:
# 3. Create a NumPy array ‘arr’ with a data type of complex128 containing three complex numbers.

arr = np.array([3+6j, 3+4j, 5+8j], dtype=np.complex128)
print(arr)
print(arr.dtype)

[3.+6.j 3.+4.j 5.+8.j]
complex128


In [6]:
# 4. Convert an existing NumPy array ‘arr’ of integers to float32 data type. 

arr = np.array([0,1,2,3,4,5], dtype=int)
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[0. 1. 2. 3. 4. 5.]
float64


In [7]:
# 5. Given a NumPy array ‘arr’ with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([2, 4, 5, 1, 9], dtype=np.float64)
print(f"Initially type of array is {arr.dtype}")
arr = arr.astype(np.float32)
print(f"After converting type of array is {arr.dtype}")

Initially type of array is float64
After converting type of array is float32


In [8]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type. 

def array_attributes(arr):
    arr_shape = arr.shape
    arr_size =arr.size
    arr_datatype = arr.dtype
    return f"Shape of arr: {arr_shape}\nSize of arr: {arr_size}\nData type of arr: {arr_datatype}"

arr = np.array([4, 6, 3, 2, 9, 8])
print(array_attributes(arr))

Shape of arr: (6,)
Size of arr: 6
Data type of arr: int64


In [9]:
# 7. Create a function array _dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):
    return f"Dimension of arr: {arr.ndim}"

arr = np.array([[2, 5, 6], [9, 5, 1]])
print(array_dimension(arr))

Dimension of arr: 2


In [10]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes. 

def item_size_info(arr):
    item_size = arr.itemsize
    total_size_bytes = arr.size * arr.itemsize
    
    return f"Item size of arr: {item_size}\nTotal size of arr in bytes: {total_size_bytes}"

arr = np.array([6, 4, 3, 6, 9, 0, 12])
print(item_size_info(arr))

Item size of arr: 8
Total size of arr in bytes: 56


In [11]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array. 

import numpy as np

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
 
print(f"Strides of the array: {array_strides(arr)}") 

Strides of the array: (24, 8)


In [12]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
# and strides of the array.

def shape_stride_relationship(arr):
    arr_shape = arr.shape
    arr_strides = arr.strides
    
    return f"Shape of arr: {arr_shape}\nStrides of arr: {arr_strides}"

arr = np.array([[[4, 6, 8], [2, 4, 6]]])
print(shape_stride_relationship(arr))

Shape of arr: (1, 2, 3)
Strides of arr: (48, 24, 8)


In [13]:
# 11. Create a function ‘create_zeros_array’ that takes an integer "n” as input and returns a NumPy array of 
# zeros with 'n” elements. 

def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [14]:
# 12. Write a function ‘create_ones_matrix’ that takes integers ‘rows™ and “cols’ as inputs and generates a 2D 
# NumPy array filled with ones of size rows x cols’.

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(4, 3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# 13. Write a function ‘generate_range_array’ that takes three integers start, stop, and step as arguments and 
# creates a NumPy array with a range starting from “start’, ending at stop (exclusive), and with the specified 
# “step’. 

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(2, 8, 2))

[2 4 6]


In [16]:
# 14. Design a function “generate_linear_space’ that takes two floats “start’, ‘stop’, and an integer 'num’ as 
# arguments and generates a NumPy array with num equally spaced values between “start” and “stop™ 
# (inclusive). 

def generate_linear_space(start, stop, n):
    return np.linspace(start, stop, n)

print(generate_linear_space(1,15,5))

[ 1.   4.5  8.  11.5 15. ]


In [17]:
# 15. Create a function ‘create_identity_matrix” that takes an integer "n" as input and generates a square 
# identity matrix of size 'n x n” using ‘numpy.eye’. 

def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
# 16. Write a function that takes a Python list and converts it into a NumPy array. 

def create_array(l):
    return np.array(l)

l = [5, 6, 3, 2, 1, 7, 3]
print(create_array(l))

[5 6 3 2 1 7 3]


In [19]:
# 17. Create a NumPy array and demonstrate the use of ‘'numpy.view’ to create a new array object with the 
# same data.

arr = np.array([[1, 2, 3], [4, 5, 6]])

view_arr = arr.view()

print(f"Original Array:\n{arr}\nView Array:\n{view_arr}")

Original Array:
[[1 2 3]
 [4 5 6]]
View Array:
[[1 2 3]
 [4 5 6]]


In [20]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concate_array(arr1, arr2, ax):
    if ax==0:
        return np.concatenate((arr1, arr2), ax)
    elif ax==1:
        return np.concatenate((arr1, arr2), ax)
    else:
        return "Axis should be 0 or 1"
    
arr1 = np.array([[3, 5, 6], [7, 8, 9]])
arr2 = np.array([[6, 0, 1], [2, 4, 5]])

print(f"array1:\n{arr1}\narray2:\n{arr2}")
print("For axis=0 array concatenate vertically:")
print(concate_array(arr1, arr2, 0))
print("For axis=1 array concatenate horizontally:")
print(concate_array(arr1, arr2, 1))

array1:
[[3 5 6]
 [7 8 9]]
array2:
[[6 0 1]
 [2 4 5]]
For axis=0 array concatenate vertically:
[[3 5 6]
 [7 8 9]
 [6 0 1]
 [2 4 5]]
For axis=1 array concatenate horizontally:
[[3 5 6 6 0 1]
 [7 8 9 2 4 5]]


In [21]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using ‘numpy. 
# concatenate’.

arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(8, 16).reshape(2, 4)

print(f"array1:\n{arr1}\narray2:\n{arr2}")
print(f"Array after concatenating horixantally:\n{np.concatenate((arr1, arr2), 1)}")

array1:
[[1 2 3]
 [4 5 6]]
array2:
[[ 8  9 10 11]
 [12 13 14 15]]
Array after concatenating horixantally:
[[ 1  2  3  8  9 10 11]
 [ 4  5  6 12 13 14 15]]


In [22]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list. 

def verticle_stack(l):
    """This finction takes list of arrays as input and returns vertically stacke all arrays in list"""
    
    return np.vstack(tuple(l))

l = [np.arange(1, 7).reshape(2, 3), np.arange(4, 16).reshape(4, 3), np.arange(3, 12).reshape(3, 3)]

for i in range(len(l)):
    print(f"array {i+1}:\n{l[i]}")
print(f"\nVertically Stacked array:\n{verticle_stack(l)}")

array 1:
[[1 2 3]
 [4 5 6]]
array 2:
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
array 3:
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Vertically Stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
# with a given step size. 

def create_array(start, stop, step):
    """This function returns an array within specified range (inclusive) woth a given step size"""
    
    return np.arange(start, stop+1, step)

print(create_array(1, 15, 2))

[ 1  3  5  7  9 11 13 15]


In [44]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
# (inclusive). 

def gnerate_array():
    return np.linspace(0, 1, 10)

print(gnerate_array())

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [33]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1and 
# 1000 (inclusive).

def logarithmic_array():
    return np.logspace(0,3,5)

print(logarithmic_array())

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [43]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
# are random integers between 1and 100. 

arr = np.random.randint(1, 100, (5, 3))
df = pd.DataFrame(arr)

print(arr, '\n', df)

[[ 9 61 60]
 [24 86 39]
 [99 67  8]
 [70 33 95]
 [71 26 72]] 
     0   1   2
0   9  61  60
1  24  86  39
2  99  67   8
3  70  33  95
4  71  26  72


In [51]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
# with zeros. Use NumPy operations within the Pandas DataFrame.

def func(df, col_name):
    df[col_name] = np.where(df[col_name] < 0, 0, df[col_name])
    return df

data = {'A': [-1, 2, -3, 4, -5, 6, 8, -9],
        'B': [10, -20, 30, -40, 50, 60, 70, 80]}
df = pd.DataFrame(data)

print(df)
df_modified = func(df, 'A')
print(df_modified)
# replaced all negative value with 0 in column A

   A   B
0 -1  10
1  2 -20
2 -3  30
3  4 -40
4 -5  50
5  6  60
6  8  70
7 -9  80
   A   B
0  0  10
1  2 -20
2  0  30
3  4 -40
4  0  50
5  6  60
6  8  70
7  0  80


In [52]:
# 26. Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50]) 
print(arr[2])

30


In [56]:
# 27.Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print(arr_2d[1, 2])
#or
print(arr_2d[1][2])

6
6


In [57]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array. 

arr = np.array([3, 8, 2, 10, 5, 7])

print(arr[arr > 5])

[ 8 10  7]


In [59]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array. 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
print(arr[2:6])

[3 4 5 6]


In [60]:
# 30. Slice the 2D NumPy array to extract the sub-array “[[2, 3], [5, 6]] from the given array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(arr_2d[0:2, 1:])

[[2 3]
 [5 6]]


In [61]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
# provided in another array. 

def extract_elements_2d(arr, indices):
    return arr[np.arange(len(arr)), indices]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([0, 2, 1])

result = extract_elements_2d(arr_2d, indices)
print("Extracted elements in specific order:", result)

Extracted elements in specific order: [1 6 8]


In [66]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
# boolean indexing.

def filter_elements(arr, n):
    return arr[arr > n]

arr = np.arange(11, 31)
print(arr)
print(filter_elements(arr, 18))

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[19 20 21 22 23 24 25 26 27 28 29 30]


In [108]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
# separate arrays for each dimension.

def extract_elements_3d(arr, indices_dim1, indices_dim2, indices_dim3):
    return arr[indices_dim1, indices_dim2, indices_dim3]

arr_3d = np.arange(1, 28).reshape(3, 3, 3)

indices_dim1 = np.array([1, 2])
indices_dim2 = np.array([2, 0])
indices_dim3 = np.array([0, 1])

result = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print(arr_3d)
print("Extracted elements from the 3D array:", result)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Extracted elements from the 3D array: [16 20]


In [109]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied 
# using boolean indexing.

def filtered_elements(arr, cond1, cond2):
    return arr[cond1 & cond2]

arr = np.arange(1, 11)
cond1 = arr > 5
cond2 = arr%2 == 0

print(arr)
print(filtered_elements(arr, cond1, cond2))

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  8 10]


In [110]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
# in separate arrays. 

def extract_from_2darray(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

arr_2d = np.arange(1, 21).reshape(5, 4)
row_indices = np.array([3, 1])
col_indices = np.array([2, 0])

print(arr_2d)
print()
print(extract_from_2darray(arr_2d, row_indices, col_indices))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

[15  5]


In [111]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting. 

arr = np.random.randint(1, 10, (3, 3))
scalar = 5
print(arr)
print(arr*scalar)

[[6 3 8]
 [1 7 5]
 [4 9 5]]
[[30 15 40]
 [ 5 35 25]
 [20 45 25]]


In [116]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
# corresponding element in arr1 using NumPy broadcasting. 

arr1 = np.random.randint(1, 5, (1, 3))
arr2 = np.random.randint(2, 8, (3, 4))

print(arr1)
print()
print(arr2)
print()
print(arr1 * arr2)

[[4 1 2]]

[[5 4 3 6]
 [2 3 7 6]
 [6 4 7 6]]



ValueError: operands could not be broadcast together with shapes (1,3) (3,4) 

In [119]:
# in above code can not brodcast with given shapes but we can transpose arr1 to (3, 1) and brodcasting can be performed
arr1 = arr1.T
print(arr1 * arr2)

[[20 16 12 24]
 [ 2  3  7  6]
 [12  8 14 12]]


In [124]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
# NumPy broadcasting.

arr1 = np.random.randint(1, 5, (1, 4))
arr2 = np.random.randint(2, 8, (4, 3))

print(arr1)
print()
print(arr2)
print()
print(arr1 + arr2)

[[1 4 4 1]]

[[2 7 4]
 [5 2 3]
 [4 7 7]
 [2 3 2]]



ValueError: operands could not be broadcast together with shapes (1,4) (4,3) 

In [125]:
# in above code can not brodcast with given shapes but we can transpose arr1 to (3, 1) and brodcasting can be performed
arr1 = arr1.T
print(arr1 + arr2)

[[ 3  8  5]
 [ 9  6  7]
 [ 8 11 11]
 [ 3  4  3]]


In [126]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
# broadcasting.

arr1 = np.random.randint(1, 5, (3, 1))
arr2 = np.random.randint(2, 8, (1, 3))

print(arr1)
print()
print(arr2)
print()
print(arr1 + arr2)

[[4]
 [2]
 [3]]

[[4 7 3]]

[[ 8 11  7]
 [ 6  9  5]
 [ 7 10  6]]


In [132]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
# broadcasting. Handle the shape incompatibility. 

arr1 = np.random.randint(1, 5, (2, 3))
arr2 = np.random.randint(2, 8, (2, 2))

arr1 = arr1.T

print(arr1)
print()
print(arr2)
print()
print(arr1 @ arr2)

[[2 3]
 [1 4]
 [2 4]]

[[2 6]
 [2 6]]

[[10 30]
 [10 30]
 [12 36]]


In [138]:
# 41. Calculate column-wise mean for the given array 

arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr)
print()
print(np.mean(arr, axis=0))

[[1 2 3]
 [4 5 6]]

[2.5 3.5 4.5]


In [139]:
# 42. Find maximum value in each row of the given array: 

arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr)
print()
print(np.max(arr, axis=1))

[[1 2 3]
 [4 5 6]]

[3 6]


In [141]:
# 43. For the given array, find indices of maximum value in each column. 

arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr)
print()
print(np.argmax(arr, axis=0))

[[1 2 3]
 [4 5 6]]

[1 1 1]


In [143]:
# 44.For the given array, apply custom function to calculate moving sum along rows. 

arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(arr):
    result = []
    for row in arr:
        moving_sum_row = []
        total = 0
        for num in row:
            total += num
            moving_sum_row.append(total)
        result.append(moving_sum_row)
    return result

print(arr)
print()
print(moving_sum(arr))

[[1 2 3]
 [4 5 6]]

[[1, 3, 6], [4, 9, 15]]


In [148]:
# 45.In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

print(arr)
print()
print(np.all(arr % 2 == 0, axis=0))

[[2 4 6]
 [3 5 7]]

[False False False]


In [152]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions ‘'m’ rows and "n” columns. Return the 
# reshaped matrix. 

original_array = np.array([1, 2, 3, 4, 5, 6])

def to_matrix(arr, m, n):
    return arr.reshape(m, n)

print(to_matrix(original_array, 2, 3))

[[1 2 3]
 [4 5 6]]


In [154]:
#47. Create a function that takes a matrix as input and returns the flattened array. 

input_matrix = np.array([[1, 2, 3], [4, 5, 6]]) 

def flattened_array(mat):
    return mat.flatten()

print(input_matrix)
print()
print(flattened_array(input_matrix))

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [159]:
#48. Write a function that concatenates two given arrays along a specified axis. 

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

def concate(arr1, arr2, ax):
    if ax==0:
        return np.concatenate((arr1, arr2), axis=0)
    elif ax==1:
        return np.concatenate((arr1, arr2), axis=1)
    else:
        return "Axis should be 0 or 1"
    
print(concate(array1, array2, 0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [164]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis. 

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(arr, num_splits, ax):
    return np.split(arr, num_splits, axis=ax)

splitted_arrays = split_array(original_array, 3, 1)
for i in splitted_arrays:
    print(i)
    print()

[[1]
 [4]
 [7]]

[[2]
 [5]
 [8]]

[[3]
 [6]
 [9]]



In [166]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5]) 
indices_to_insert = [2, 4] 
values_to_insert = [10, 11] 
indices_to_delete = [1, 3]

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)
    
    modified_array = np.delete(modified_array, indices_to_delete)

    return modified_array

result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Original array:", original_array)
print("Array after insertions and deletions:", result_array)

Original array: [1 2 3 4 5]
Array after insertions and deletions: [ 1 10  4 11  5]


In [172]:
# 51. Create a NumPy array “arr1” with random integers and another array “arr2’ with integers from 1to 10. 
# Perform element-wise addition between “arr1” and “arr2’. 

arr1 = np.random.randint(1, 10, (2, 5))
arr2 = np.arange(1, 11).reshape(2, 5)

print(arr1)
print()
print(arr2)
print()
print(arr1 + arr2)

[[3 4 7 6 9]
 [6 4 8 4 3]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 4  6 10 10 14]
 [12 11 16 13 13]]


In [174]:
# 52. Generate a NumPy array “arr1” with sequential integers from 10 to 1 and another array “arr2” with integers 
# from 1to 10. Subtract “arr2’ from “arr1” element-wise.

arr1 = np.arange(10, 0, -1).reshape(2, 5)
arr2 = np.arange(1, 11).reshape(2, 5)

print(arr1)
print()
print(arr2)
print()
print(arr1 - arr2)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 9  7  5  3  1]
 [-1 -3 -5 -7 -9]]


In [177]:
# 53. Create a NumPy array "arr1" with random integers and another array “arr2’ with integers from 1to 5. 
# Perform element-wise multiplication between “arr1” and “arr2". 

arr1 = np.random.randint(1, 10, (5, 1))
arr2 = np.arange(1, 6).reshape(1, 5)

print(arr1)
print()
print(arr2)
print()
print(arr1 * arr2)

[[7]
 [9]
 [6]
 [2]
 [1]]

[[1 2 3 4 5]]

[[ 7 14 21 28 35]
 [ 9 18 27 36 45]
 [ 6 12 18 24 30]
 [ 2  4  6  8 10]
 [ 1  2  3  4  5]]


In [179]:
# 54. Generate a NumPy array “arr1” with even integers from 2 to 10 and another array “arr2’ with integers from 1 
# to 5. Perform element-wise division of “arr1” by “arr2’. 

arr1 = np.arange(2, 11, 2).reshape(1, 5)
arr2 = np.arange(1, 6).reshape(1, 5)

print(arr1)
print()
print(arr2)
print()
print(arr1 / arr2)

[[ 2  4  6  8 10]]

[[1 2 3 4 5]]

[[2. 2. 2. 2. 2.]]


In [182]:
# 55. Create a NumPy array “arr1’ with integers from 1to 5 and another array “arr2” with the same numbers 
# reversed. Calculate the exponentiation of “arr1” raised to the power of “arr2” element-wise.

arr1 = np.arange(1, 6).reshape(1, 5)
arr2 = np.arange(5, 0, -1).reshape(1, 5)

print(arr1)
print()
print(arr2)
print()
print(np.power(arr1, arr2))

[[1 2 3 4 5]]

[[5 4 3 2 1]]

[[ 1 16 27 16  5]]


In [183]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings. 

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello']) 

def count_substring(arr, substr):
    count = 0
    for i in arr:
        count += i.count(substr)
        
    return count

substr = 'hello'
print(f"The substring '{substr}' occurs {count_substring(arr, substr)} times in the array.")

The substring 'hello' occurs 3 times in the array.


In [190]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase_chars(arr):
    uppercase_chars = [char for string in arr for char in string if char.isupper()]
    
    return uppercase_chars

uppercase_chars = extract_uppercase_chars(arr)
print("Uppercase characters:", uppercase_chars)

Uppercase characters: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [191]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string. 

arr = np.array(['apple', 'banana', 'grape', 'pineapple']) 

def replace_substring(arr, old_substr, new_substr):
    for i in range(len(arr)):
        arr[i] = arr[i].replace(old_substr, new_substr)
    return arr

old_substr = 'apple'
new_substr = 'orange'
new_arr = replace_substring(arr, old_substr, new_substr)
print("Modified array:", new_arr)

Modified array: ['orange' 'banana' 'grape' 'pineorang']


In [207]:
#59. Write a function that concatenates strings in a NumPy array element-wise. 
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI']) 

def concate_string_array(arr1, arr2):
    return np.array([arr1[i]+arr2[i] for i in range(len(arr1))])

print(concate_string_array(arr1, arr2))

['HelloOpen' 'WorldAI']


In [208]:
#60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_string_length(arr):
    str_len = [len(i) for i in arr]
    return max(str_len)

print(longest_string_length(arr))

9


In [209]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
# standard deviation of the dataset using NumPy's functions. 

dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)

median = np.median(dataset)

variance = np.var(dataset)

std_deviation = np.std(dataset)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Mean: 475.59
Median: 546.5
Variance: 91478.9819
Standard Deviation: 302.4549254021167


In [211]:
# 62. Generate an array of 50 random numbers between 1and 100. Find the 25th and 75th percentiles of the 
# dataset.

arr = np.random.randint(1, 100, size=50)

percentile_25th = np.percentile(arr, 25)
percentile_75th = np.percentile(arr, 75)

print("25th percentile:", percentile_25th)
print("75th percentile:", percentile_75th)

25th percentile: 28.5
75th percentile: 65.0


In [227]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
# arrays using NumPy's 'corrcoef' function. 

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Compute the correlation coefficient
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Correlation coefficient between the two arrays:", round(correlation_coefficient, 2))

Correlation coefficient between the two arrays: -1.0


In [229]:
# 64. Create two matrices and perform matrix multiplication using NumPy's 'dot' function.

arr1 = np.random.randint(1, 5, (3, 3))
arr2 = np.random.randint(1, 5, (3, 3))

print(arr1)
print()
print(arr2)
print()
print(np.dot(arr1, arr2))

[[3 3 3]
 [3 4 3]
 [2 4 2]]

[[1 3 2]
 [3 4 1]
 [1 1 3]]

[[15 24 18]
 [18 28 19]
 [16 24 14]]


In [244]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
# percentiles along with the first and third quartiles. 

arr = np.random.randint(10, 1000, (50,))
print(arr)
print()
print("10th percentile:", np.percentile(arr, 10))
print("50th percentile(median):", np.median(arr))
print("90th percentile:", np.percentile(arr, 90))
print("25th percentile(first quartile):", np.percentile(arr, 25))
print("75th percentile(third quartile):", np.percentile(arr, 75))

[405 935 480 427 778 217 497 597 753 925 831 131 440 246 705 106 139 146
 908 168 810 660 491 310 100 833 262 189 754 191 222 959 152 313 550 206
 527 319 871 466 442 561 159 516  45 453 822 425 881  50]

10th percentile: 138.2
50th percentile(median): 447.5
90th percentile: 872.0
25th percentile(first quartile): 208.75
75th percentile(third quartile): 741.0


In [245]:
# 66. Create a NumPy array of integers and find the index of a specific element. 

arr = np.array([10, 20, 30, 40, 50])
element = 30

index = np.where(arr == element)[0]

print(f"Index of {element}: {index}")

Index of 30: [2]


In [252]:
# 67. Generate a random NumPy array and sort it in ascending order. 

arr = np.random.randint(1, 100, 30)
print(arr)
print(f"Sorted array: {np.sort(arr)}")

[83 30 29 60 16 79 34 88 71  1 10  8 55 57 71 81  8 98 19 28  4 24 21 60
 99 43 86 11 53 93]
Sorted array: [ 1  4  8  8 10 11 16 19 21 24 28 29 30 34 43 53 55 57 60 60 71 71 79 81
 83 86 88 93 98 99]


In [253]:
# 68. Filter elements >20 in the given NumPy array. 
arr = np.array([12, 25, 6, 42, 8, 30]) 

print(arr[arr > 20])

[25 42 30]


In [254]:
#69. Filter elements which are divisible by 3 from a given NumPy array. 
arr = np.array([1, 5, 8, 12, 15])

print(arr[arr%3==0])

[12 15]


In [256]:
#70. Filter elements which are >= 20 and <= 40 from a given NumPy array. 
arr = np.array([10, 20, 30, 40, 50]) 

print(arr[(arr >= 20) & (arr <= 40)])

[20 30 40]


In [257]:
#71. For the given NumPy array, check its byte order using the 'dtype' attribute byteorder. 
arr = np.array([1, 2, 3]) 

print(arr.dtype.byteorder)

=


In [258]:
#72.For the given NumPy array, perform byte swapping in place using 'byteswap()'. 
arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(True)

print("Array after byte swapping:", arr)

Array after byte swapping: [16777216 33554432 50331648]


In [259]:
#73. For the given NumPy array, swap its byte order without modifying the original array using 'newbyteorder()'. 
arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print("Original Array:", arr)
print("Swapped Byte Order Array:", swapped_arr)

Original Array: [1 2 3]
Swapped Byte Order Array: [16777216 33554432 50331648]


In [261]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using 'newbyteorder()'. 
arr = np.array([1, 2, 3], dtype=np.int32)

system_endianness = np.dtype(np.int32).byteorder

if system_endianness != arr.dtype.byteorder:
    swapped_arr = arr.newbyteorder()

    print("Original Array:", arr)
    print("Swapped Byte Order Array:", swapped_arr)
else:
    print("System endianness matches array byte order. No need to swap.")
    print("Array:", arr)

System endianness matches array byte order. No need to swap.
Array: [1 2 3]


In [262]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using “dtype” 
# attribute "byteorder". 
arr = np.array([1, 2, 3], dtype=np.int32)

system_endianness = np.dtype(np.int32).byteorder

if system_endianness != arr.dtype.byteorder:
    print("Byte swapping is necessary for the current system.")
else:
    print("No byte swapping is necessary for the current system.")

No byte swapping is necessary for the current system.


In [296]:
# 76. Create a NumPy array “arr1” with values from 1to 10. Create a copy of “arr1’ named ‘copy_arr” and modify 
# an element in “copy_arr". Check if modifying ‘copy_arr affects “arr1". 

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 2

print(f"Original array: {arr1}")
print(f"Copied array after modification: {copy_arr}")

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Copied array after modification: [ 2  2  3  4  5  6  7  8  9 10]


In [297]:
# 77. Create a 2D NumPy array "matrix" of shape (3, 3) with random integers. Extract a slice “view_slice” from 
# the matrix. Modify an element in “view_slice” and observe if it changes the original "matrix" . 

matrix = np.random.randint(1, 10, (3, 3))
view_slice = matrix[1]

print(f"Original array\n:{matrix}")
print(f"View slice: {view_slice}")

view_slice[2] = 12

print(f"View slice after modification: {view_slice}")
print(f"Original array after modification view slice\n:{matrix}")

Original array
:[[3 4 8]
 [8 2 2]
 [6 8 6]]
View slice: [8 2 2]
View slice after modification: [ 8  2 12]
Original array after modification view slice
:[[ 3  4  8]
 [ 8  2 12]
 [ 6  8  6]]


In [306]:
# 78. Create a NumPy array "array_a" of shape (4, 3) with sequential integers from 1to 12. Extract a slice 
# "view_b" from "array_a" and broadcast the addition of 5 to view_b. Check if it alters the original “array_a". 

array_a = np.arange(1, 13).reshape(4,3)

view_b = array_a[1]

print(f"Original array\n:{array_a}")
print(f"view_b slice: {view_b}")

view_b = view_b + 5

print(f"view_b slice after brodcasting: {view_b}")
print(f"Original array after brodcasting view_b slice\n:{array_a}")

Original array
:[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
view_b slice: [4 5 6]
view_b slice after brodcasting: [ 9 10 11]
Original array after brodcasting view_b slice
:[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [307]:
# 79. Create a NumPy array 'orig_array' of shape (2, 4) with values from 1to 8. Create a reshaped view 
# 'reshaped_view' of shape (4, 2) from orig_array. Modify an element in ‘reshaped_view’ and check if it 
# reflects changes in the original 'orig_array'.

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.T

print(f"Original array:\n{orig_array}")
print(f"Reshaped View:\n{reshaped_view}")

reshaped_view[2][1] = 9

print(f"Reshaped View after modifying :\n{reshaped_view}")
print(f"Original array after modifying reshaped view:\n{orig_array}")

Original array:
[[1 2 3 4]
 [5 6 7 8]]
Reshaped View:
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
Reshaped View after modifying :
[[1 5]
 [2 6]
 [3 9]
 [4 8]]
Original array after modifying reshaped view:
[[1 2 3 4]
 [5 6 9 8]]


In [308]:
# 80. Create a NumPy array 'data' of shape (3, 4) with random integers. Extract a copy 'data_copy' of 
# elements greater than 5. Modify an element in “data_copy” and verify if it affects the original ‘data’. 

data = np.random.randint(1, 10, (3, 4))
data_copy = data[data > 5]

print(f"Original array:\n{data}")
print(f"Data_copy:\n{data_copy}")

data_copy[2] = 15

print(f"Data_copy after modifying:\n{data_copy}")
print(f"Original array after modifying data_copy:\n{data}")

Original array:
[[2 6 2 4]
 [8 4 3 4]
 [9 1 7 9]]
Data_copy:
[6 8 9 7 9]
Data_copy after modifying:
[ 6  8 15  7  9]
Original array after modifying data_copy:
[[2 6 2 4]
 [8 4 3 4]
 [9 1 7 9]]


In [311]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
# operations between them.

A = np.random.randint(1, 5, (3, 3))
B = np.random.randint(4, 9, (3, 3))

print(f"array A:\n{A}")
print(f"array B:\n{B}")

print(f"Addition of arrays:\n{A+B}")
print(f"Subtraction of arrays:\n{A-B}")

array A:
[[4 2 3]
 [2 4 4]
 [3 3 3]]
array B:
[[4 4 8]
 [7 7 5]
 [6 4 8]]
Addition of arrays:
[[ 8  6 11]
 [ 9 11  9]
 [ 9  7 11]]
Subtraction of arrays:
[[ 0 -2 -5]
 [-5 -3 -1]
 [-3 -1 -5]]


In [314]:
# 82. Generate two matrices "C" (3x2) and "D" (2x4) and perform matrix multiplication. 

C = np.random.randint(1, 5, (3, 2))
D = np.random.randint(1, 5, (2, 4))

print(f"Matrix multiplication of array C and D:\n{C @ D}")

Matrix multiplication of array C and D:
[[15 14 15 17]
 [ 6  5  6  7]
 [18 15 18 21]]


In [316]:
# 83. Create a matrix "E" and find its transpose. 

E = np.arange(1, 13).reshape(2, 6)
E_transpose = E.T

print(f"Matrix E:\n{E}")
print(f"Transpose of E:\n{E_transpose}")

Matrix E:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Transpose of E:
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [322]:
# 84. Generate a square matrix "F" and compute its determinant.

F = np.arange(1, 10).reshape(3, 3)

determinant = np.linalg.det(F)

print(f"Matrix F:\n{F}")
print(f"Determinant of Matrix F: {determinant}")

Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of Matrix F: 0.0


In [323]:
# 85. Create a square matrix “G” and find its inverse.

G = np.random.randint(1, 5, (2, 2))
inverse_G = np.linalg.inv(G)

print(f"Matrix G:\n{G}")
print(f"Inverse of Matrix G:\n{inverse_G}")

Matrix G:
[[2 4]
 [1 1]]
Inverse of Matrix G:
[[-0.5  2. ]
 [ 0.5 -1. ]]
